### PR TITLE
feat: update framework packages to 2.2.x

### PR DESCRIPTION
**Pull request by anthony9187**
## Description

This PR updates the lightningtv solid and core dependencies to their latest versions

## Changes
- updates solid and core packages
- replaces IntrinsicProps usages with Node/TextProps
- updates the TextStyleSet to work correctly, removes a bunch of unnecessary types from types.ts
- removes a handful of no-longer-necessary ts-expect-error statements 🥳
- fixes broken fonts when navigating between stories(renderer update)
- convert numbers to strings in FPSCounter

## Testing

ensure storybook renderers components as expected
ensure storybook static site builds
ensure library builds
(last two are technically covered by smoke tests)

### CODE REVIEW

**Comment by chiefcll** [comment]
So weird I can't see this branch locally... Not sure if it's because it's a draft?

**Comment by anthony9187** [comment]
> So weird I can't see this branch locally... Not sure if it's because it's a draft?

that's so strange, the branch should still appear either way 🤔

**Comment by cee-money** [comment]
> > So weird I can't see this branch locally... Not sure if it's because it's a draft?
> 
> that's so strange, the branch should still appear either way 🤔

I was able to access it! Maybe need to re-fetch?

**Review by cee-money — APPROVED** [review]
stories working as expected as well as build scripts!

LGTM

**Pull request merged**
